### ISSUE TITLE
letter O missing first `dah` in audio in web browser and audio download

### ISSUE THREAD

**Issue by joecabezas** [scp93ch/morse-pro#8]
hello, great project
I already read the FAQ
https://morsecode.world/faq.html

I understand audio issues with delay, but even the download audio has a missing `dah` on letter O

this is only wrong on trainer mode:
https://morsecode.world/american/trainer.html

letter O is ok in translator:
https://morsecode.world/international/translator.html

example audio:
[ONTJS.zip](https://github.com/scp93ch/morse-pro/files/10857716/ONTJS.zip)

have a nice day

**Comment by scp93ch** [comment]
Hi,

Thanks for the report.

In the "trainer mode" where you say the "O" is wrong, you're looking at the American ("Railroad") Morse rather than the International Morse that you're probably expecting.

You can see that "O" in American Morse is two separated dits here: https://morsecode.world/american/morse.html

The library that creates the sounds has actually moved to GitLab: https://gitlab.com/scphillips/morse-pro

Stephen.
